// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYmTALBk1ityYNDEuIxRttHLFqauKtOI',
    appId: '1:979823982569:web:038bfadedc8ffd6a39fd78',
    messagingSenderId: '979823982569',
    projectId: 'testing-cli-23634',
    authDomain: 'testing-cli-23634.firebaseapp.com',
    storageBucket: 'testing-cli-23634.firebasestorage.app',
    measurementId: 'G-M054MPDJ0S',
  );

 static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyDn-muHCrWHwwHdod21gK_PxQWQ_T4dljU',
  appId: '1:979823982569:android:8c4373e28a8ef19a39fd78',
  messagingSenderId: '979823982569',
  projectId: 'dummy-335c3',
  storageBucket: 'dummy-335c3.appspot.com', // ✅ fixed here
);


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyMK5p8qcUVh1NqjlUvCqiBhOWfL7eUIQ',
    appId: '1:979823982569:ios:16f946f7a786169539fd78',
    messagingSenderId: '979823982569',
    projectId: 'testing-cli-23634',
    storageBucket: 'testing-cli-23634.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyMK5p8qcUVh1NqjlUvCqiBhOWfL7eUIQ',
    appId: '1:979823982569:ios:16f946f7a786169539fd78',
    messagingSenderId: '979823982569',
    projectId: 'testing-cli-23634',
    storageBucket: 'testing-cli-23634.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTYmTALBk1ityYNDEuIxRttHLFqauKtOI',
    appId: '1:979823982569:web:1bffcb242c71381b39fd78',
    messagingSenderId: '979823982569',
    projectId: 'testing-cli-23634',
    authDomain: 'testing-cli-23634.firebaseapp.com',
    storageBucket: 'testing-cli-23634.firebasestorage.app',
    measurementId: 'G-Z0MRGKVR1Q',
  );
}
